package dev.clojurephant.plugin.clojurescript.tasks;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

import javax.inject.Inject;

import dev.clojurephant.plugin.common.internal.Edn;
import org.gradle.api.DefaultTask;
import org.gradle.api.file.RegularFileProperty;
import org.gradle.api.model.ObjectFactory;
import org.gradle.api.provider.Property;
import org.gradle.api.tasks.Nested;
import org.gradle.api.tasks.OutputFile;
import org.gradle.api.tasks.TaskAction;

public class WriteFigwheelOptions extends DefaultTask {
  private final Property<FigwheelOptions> options;
  private final RegularFileProperty destinationFile;

  @Inject
  public WriteFigwheelOptions(ObjectFactory objects) {
    this.options = objects.property(FigwheelOptions.class);
    this.destinationFile = objects.fileProperty();
  }

  @TaskAction
  public void write() throws IOException {
    List<String> lines = List.of(
        ";; DO NOT MODIFY: This file was autogenerated by clojurephant",
        Edn.print(options.get()));
    Path path = destinationFile.get().getAsFile().toPath();
    Files.write(path, lines, StandardCharsets.UTF_8);
  }

  @Nested
  public Property<FigwheelOptions> getOptions() {
    return options;
  }

  @OutputFile
  public RegularFileProperty getDestinationFile() {
    return destinationFile;
  }
}
