= Introduction

Clojurephant (link:https://github.com/clojurephant/clojurephant[GitHub Repo]) is a Gradle plugin providing support for Clojure and ClojureScript projects.

WARNING: clojurephant should not be considered stable before v1.0. Until then, minor versions will often contain breaking changes.

== Rationale

Gradle is a popular build tool in the JVM ecosysytem with a rich plugin ecosystem and support for polyglot projects.

In particular, if you have a need to interop with Java code (maybe even other JVM languages), Gradle provides a good base of support.

== Features

=== Gradle

Features provided by Gradle (or its ecosystem) that are useful for Clojure programmers.

* Packaging into ZIPs, JARs, or Uberjars (via the third-party link:http://imperceptiblethoughts.com/shadow/[Shadow plugin])
* Multi-project builds
* Publishing to Maven repositories (such as Clojars or Maven Central)

=== Clojure/ClojureScript

Unique features provided by Clojurephant.

* Running `clojure.test` tests with Gradle's out-of-box `Test` task (via the link:https://github.com/ajoberstar/jovial[jovial] Junit Platform Engine)
* Clojure AOT compilation
* ClojureScript compilation (supporting multiple builds)
* Running an nREPL server (supporting custom middleware or handlers)
** Supporting "jack-in" dependencies
** Enriching classpath with dependencies' sources/javadoc by default

CAUTION: ClojureScript features, in particular, are not fully settled and may change before 1.0.

== Release Notes

See the link:https://github.com/clojurephant/clojurephant/releases[GitHub releases] for the changelog of each version.

== Quick Start

Look at our sample projects:

* link:https://github.com/clojurephant/sample-clojurephant-clj-lib[]
* link:https://github.com/clojurephant/sample-clojurephant-clj-app[]
* link:https://github.com/clojurephant/sample-clojurephant-cljs-app[]

If the samples or our documentation doesn't answer your questions, please ask in link:https://github.com/clojurephant/clojurephant/discussions[Clojurephant Discussions].

== Project Layout

This the default layout, which can be configured via Gradle's `sourceSets` extension.

----
<project>/
  settings.gradle
  build.gradle
  gradlew
  gradlew.bat
  gradle/
    wrapper/
      gradle-wrapper.jar
      gradle-wrapper.properties
  src/
    main/
      clojure/
        sample_clojure/
          core.clj
      clojurescript/
        sample_clojure/
          main.cljs
    test/
      clojure/
        sample_clojure/
          core_test.clj
      clojurescript/
        sample_clojure/
          main_test.cljs // right now we don't support cljs.test
    dev/
      clojure/
        user.clj
      clojurescript/
        user.cljs
----

== Build Script

A sample, relatively complete build file for a full-stack project looks like this:

.build.gradle
[source, groovy, subs="attributes"]
----
plugins {
  id 'dev.clojurephant.clojure' version '{clojurephant-version}'
  id 'dev.clojurephant.clojurescript' version '{clojurephant-version}'
}

repositories {
  mavenCentral()
  maven {
    name = 'clojars'
    url = 'https://repo.clojars.org'
  }
}

dependencies {
  // clojure
  implementation 'org.clojure:clojure:{clojure-version}'
  implementation 'org.clojure:clojurescript:{clojurescript-version}'

  // testing
  testRuntimeOnly 'org.ajoberstar:jovial:{jovial-version}'

  // backend
  implementation 'io.pedestal:pedestal.service:{pedestal-version}'
  implementation 'io.pedestal:pedestal.jetty:{pedestal-version}'

  // frontend
  implementation 're-frame:re-frame:{reframe-version}'

  // component
  implementation 'com.stuartsierra:component:{component-version}'
  devImplementation 'com.stuartsierra:component.repl:{component-repl-version}'

  // figwheel
  devImplementation 'com.bhauman:figwheel-repl:{figwheel-repl-version}'
  devImplementation 'ring:ring-jetty-adapter:{ring-jetty-adapter-version}'
}

tasks.withType(Test) {
  useJUnitPlatform()
}

clojure {
  builds {
    main {
      aotNamespaces.add('sample.core')
      reflection = 'warn'
    }
  }
}

clojurescript {
  builds {
    all {
      compiler {
        outputTo = 'public/js/main.js'
        outputDir = 'public/js/out'
        assetPath = '/js/out'
        main = 'sample.main'
      }
    }
    main {
      compiler {
        optimizations = 'advanced'
        sourceMap = 'public/js/main.js.map'
      }
    }
    dev {
      compiler {
        optimizations = 'none'
        sourceMap = true
        preloads = ['sample.dev']
      }
    }
  }
}
----

== Documentation

Documentation is divided into sections based on your need:

* xref:tutorials:new-gradle.adoc[] - learning-oriented
* xref:howto:faq.adoc[] - task-oriented
* xref:reference:index.adoc[] - information-oriented
* xref:explanation:index.adoc[] - understanding-oriented

Many of these sections are still under-construction so please give feedback on what would be most useful to you.
