= Java Support

Applies the Gradle built-in `java-base` plugin to get basic support for the JVM ecosystem.

The high-level features provided by `java-base` for each link:https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/SourceSet.html[SourceSet].

Each source set will have a Java compilation task `compile<Name>Java` task (`compileJava` for the `main` source set).

== Dependencies

Multiple dependency "buckets" are created for each source set, to allow scoping them to the places their needed.

Names below are for a source set named `main`. Other source sets' configurations will be prefixed by the source set name (e.g. `testRuntimeOnly`).

** `compileOnly` for dependencies only needed at compile time, but shouldn't be pulled in transitively by consumers
** `implementation` for dependencies your code needs to compile and needed by your consumers
** `runtimeOnly` for dependencies your code needs to run, but aren't necessary at compile time

== Project Layout

This is the default project layout for a source set.

----
settings.gradle
build.gradle
src/
  <source set name>/
    java/
    resources/
----

== Creating a SourceSet

.build.gradle
[source, groovy]
----
sourceSets {
  myStuff {
    java.srcDirs = ['src/myjava']
    resources.srcDirs = ['src/myresources']
  }
}

dependencies {
  implementation 'org.slf4j:slf4j-api:1.7.0'
  runtimeOnly 'ch.qos.logback:logback-classic:1.2.11'
}
----

== JVM Toolchain

Gradle's link:https://docs.gradle.org/current/userguide/toolchains.html[JVM toolchain] feature allows you to declare a specific JVM version to use for its tasks. This means that Gradle can run on one JVM version and your tasks can run on another. Or you can have different tasks run on different JVMs.

By default, Gradle will try to detect installed JVM versions from your device and if the requested version is not found it will download it for you.

In the simplest case, you declare a JVM version to use for all tasks that fork a JVM. This is supported by the tasks created by the Java plugins and all tasks created by the Clojurephant plugins.

.build.gradle
[source, groovy]
----
java {
  toolchain {
    languageVersion = JavaLanguageVersion.of(17)
  }
}
----
